
services:
  mongo:
    image: mongo:8
    container_name: ims_mongo
    restart: always
    ports:
      - "27017:27017"
    volumes:
      - mongo_data:/data/db
    networks:
      - ims_net

  frontend:
    image: ghcr.io/codemonix/ims_frontend:latest
    restart: unless-stopped
    networks:
      - ims_net
    environment:
      - API_BASE=/api     # recommended to set to /ims/api on host
      - BASE_PATH=

  backend:
    image: ghcr.io/codemonix/ims_backend:latest
    restart: unless-stopped
    networks:
      - ims_net
    environment:
      - NODE_ENV=production

  host-nginx:
    image: nginx:1.25-alpine
    restart: unless-stopped
    volumes:
      - ./host-nginx/nginx.conf:/etc/nginx/nginx.conf:ro
    ports:
      - "80:80"
    networks:
      - ims_net

networks:
  ims_net:
    driver: bridge

volumes:
  mongo_data:
