import { Response, NextFunction } from 'express';
import fs from 'fs';
import * as systemService from '../services/system.service.js';
import logger from '../utils/logger.js';
import { AppError } from '../errors/AppError.js';
import { AuthenticatedRequest } from '../types/auth.types.js';
import { IFactoryResetBody, IClearDataBody } from '../types/system.types.js';

export const createBackup = async (
    req: AuthenticatedRequest, 
    res: Response, 
    next: NextFunction
): Promise<void> => {
    try {
        const fileName = `ims_backup_${new Date().toISOString().split('T')[0]}.zip`;
        res.attachment(fileName); 
        
        await systemService.streamBackupToClient(res);

        logger.info(`System backup generated by ${req.user.email}`, { 
            type: 'audit', action: 'BACKUP', userId: req.user._id 
        });
        res.status(200).json({ success: true, message: "Backup generated successfully." });
    } catch (error) {
        if (!res.headersSent) next(error);
    }
};

export const restoreBackup = async (
    req: AuthenticatedRequest, 
    res: Response, 
    next: NextFunction
): Promise<void> => {
    try {
        if (!req.file) {
            return next(new AppError("No backup file uploaded", 400));
        }

        await systemService.restoreFromBackup(req.file.path);

        logger.info(`System restored from backup by ${req.user.email}`, { 
            type: 'audit', action: 'RESTORE', userId: req.user._id 
        });
        res.status(200).json({ success: true, message: "System restored successfully." });
    } catch (error) {
        next(error);
    } finally {
        if (req.file && fs.existsSync(req.file.path)) {
            fs.unlinkSync(req.file.path);
        }
    }
};

export const factoryReset = async (
    req: AuthenticatedRequest<any, any, IFactoryResetBody>, 
    res: Response, 
    next: NextFunction
) => {
    try {
        if (req.body.confirmation !== 'DELETE EVERYTHING') {
            return next(new AppError("Invalid confirmation phrase.", 400));
        }

        await systemService.executeFactoryReset();

        logger.warn(`FACTORY RESET EXECUTED BY ${req.user.email}`, { 
            type: 'audit', action: 'FACTORY_RESET', userId: req.user._id 
        });
        res.status(200).json({ success: true, message: "Factory reset complete." });
    } catch (error) {
        next(error);
    }
};

export const clearData = async (
    req: AuthenticatedRequest<any, any, IClearDataBody>, 
    res: Response, 
    next: NextFunction
) => {
    try {
        await systemService.clearSpecificData(req.body.target);
        
        logger.info(`${req.body.target} data cleared by ${req.user.email}`, { 
            type: 'audit', action: 'CLEAR_DATA', userId: req.user._id 
        });
        res.status(200).json({ success: true, message: `All ${req.body.target} cleared successfully.` });
    } catch (error) {
        next(error);
    }
};