name: Frontend CI

on:
    push:
      branches: [ master ]
      paths:
            - 'client/**'
            - '.github/workflows/frontend-ci.yml'
    pull_request:
        paths:
            - 'client/**'

jobs:
    frontend-tests-and-push:
        runs-on: ubuntu-latest

        steps:
            - name: Checkout code
              uses: actions/checkout@v3

            - name: Set up Node.js
              uses: actions/setup-node@v3
              with:
                node-version: '22'


            - name: Install dependencies
              run: npm install
              working-directory: ./client

            - name: Run tests
              run: npm run test
              working-directory: ./client

            - name: Build frontend
              run: npm run build
              working-directory: ./client

            - name: Setup Docker Buildx
              uses: docker/setup-buildx-action@v3

            - name: Log in to GHCR
              uses: docker/login-action@v3
              with:
                registry: ghcr.io
                username: ${{ secrets.GHCR_USERNAME }}
                password: ${{ secrets.GHCR_TOKEN }}

            - name: Build and Push Frontend Docker Image
              uses: docker/build-push-action@v5
              with:
                context: ./client
                push: true
                tags: ghcr.io/${{ secrets.GHCR_USERNAME }}/ims_frontend:latest

            - name: SSH deploy frontend to VPS
              uses: webfactory/ssh-agent@v0.9.0
              with:
                ssh-private-key: ${{ secrets.VPS_SSH_KEY }}

            # - name: Restart frontend via SSH
            #   run: |
            #     ssh -o StrictHostKeyChecking=no ${{ secrets.VPS_USER }}@${{ secrets.VPS_HOST }} << 'EOF'
            #       cd /home/ubuntu/app/IMS
            #       docker pull ghcr.io/${{ secrets.GHCR_USERNAME }}/ims_frontend:latest
            #       docker compose up -d
            #     EOF